## config/default.yaml
hydra:
  run:
    dir: ${exp_dir}
  output_subdir: null

defaults:
  - _self_
  - langevin_diffusion: null
  - diffuser: null
  - model: null
  - task: null
  - optimizer: null
  - planner: null

output_dir: checkpoints
exp_name: default
exp_dir: ${output_dir}/${exp_name}/${now:%Y-%m-%d-%H-%M-%S}

slurm: false
gpus: [0, 1, 2, 3]

## for saving model
no_logging: false
no_checkpointing: false

save_model_interval: 1
save_model_seperately: false
save_scene_model: false # save scene model or not, important!!!